GET http://localhost:5001/subscribers

###

GET http://localhost:5001/subscribers/69e6363a5449a6428d1168a2

###
POST http://localhost:5001/subscribers
Content-Type: application/json

{
    "name":"chitti",
    "subscribedToChannel":"chittichannel"
}

###
DELETE http://localhost:5001/subscribers/69e6363a5449a6428d1168a2

###
PATCH http://localhost:5001/subscribers/69e6363a5449a6428d1168a2
Content-Type: application/json  

{
  "name": "Test User",
  "subscribedToChannel": "Test Channel"
}

###
POST http://localhost:5001/auth/register
Content-Type: application/json

{
   "email": "user3@gmail.com",
   "password": "123"
}

###
POST http://localhost:5001/auth/login
Content-Type: application/json

{
  "email": "user3@gmail.com",
  "password": "123"
}

###
GET http://localhost:5001/auth/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWU2YzdkNDJhNDFjM2FmMTI0OWU4NDEiLCJpYXQiOjE3NzY3ODkwNTcsImV4cCI6MTc3Njc5MjY1N30.EEwxPfLa_yvdgJFtdXMQng3_C7ucJZ--tetH82TVqt4
###
GET http://localhost:5001/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWU2YzdkNDJhNDFjM2FmMTI0OWU4NDEiLCJpYXQiOjE3NzY3ODkwNTcsImV4cCI6MTc3Njc5MjY1N30.EEwxPfLa_yvdgJFtdXMQng3_C7ucJZ--tetH82TVqt4
###
POST http://localhost:5001/auth/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWU2YzdkNDJhNDFjM2FmMTI0OWU4NDEiLCJpYXQiOjE3NzY3ODkwNTcsImV4cCI6MTc3Njc5MjY1N30.EEwxPfLa_yvdgJFtdXMQng3_C7ucJZ--tetH82TVqt4
Content-Type: application/json

{
  "title": "Test Post",
  "content": "Hello world"
}

###
GET http://localhost:5001/auth/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWU2YzdkNDJhNDFjM2FmMTI0OWU4NDEiLCJpYXQiOjE3NzY3ODkwNTcsImV4cCI6MTc3Njc5MjY1N30.EEwxPfLa_yvdgJFtdXMQng3_C7ucJZ--tetH82TVqt4

###
DELETE http://localhost:5001/auth/posts/69e7a6738b190c4f82e9c461
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWU2YzdkNDJhNDFjM2FmMTI0OWU4NDEiLCJpYXQiOjE3NzY3ODkwNTcsImV4cCI6MTc3Njc5MjY1N30.EEwxPfLa_yvdgJFtdXMQng3_C7ucJZ--tetH82TVqt4


